fix: remove workos
Green-Kittens/bathroom-finder-backend pull request #19
Opened 2024-04-30 03:28 UTC by dylantompkins

2024-04-30 07:23 UTC, JonasSchiessl requested changes

2024-04-30 07:23 UTC, JonasSchiessl commented on package.json
can you remove:
 "iron-session": "^8.0.1",
  "jose": "^5.2.4",
"@workos-inc/node": "^7.0.0",
 "cookie-parser": "^1.4.6",
"@types/cookie-parser": "^1.4.7",

2024-05-01 18:32 UTC, dltompki commented on package.json
completed in https://github.com/Green-Kittens/bathroom-finder-backend/pull/19/commits/e61b2830c7df195132a132b7494b330ee39befd8

2024-05-01 19:14 UTC, JonasSchiessl approved these changes

2024-05-01 19:14 UTC, merged